version: '3.8'

services:
  file-cloud:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - FLASK_ENV=production
    container_name: file-cloud-prod
    ports:
      - "80:5000"  # Map to port 80 for production
    volumes:
      # Persistent storage for uploads and database
      - file_cloud_uploads:/app/uploads
      - file_cloud_db:/app/instance
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - PYTHONUNBUFFERED=1
    restart: always
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: file-cloud-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - file-cloud
    restart: always
    profiles: ["with-nginx"]

volumes:
  file_cloud_uploads:
    driver: local
  file_cloud_db:
    driver: local

networks:
  default:
    driver: bridge